spring.datasource.url: jdbc:mysql://localhost:3306/AffairLib
spring.datasource.username: root
spring.datasource.password: password
spring.jpa.hibernate.ddl-auto: none
spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
spring.jpa.generate-ddl: true
